name: Build Audio Share on Alpine
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install system dependencies
        shell: sh
        run: |
          apk update
          apk add --no-cache \
            git \
            build-base \
            cmake \
            pipewire-dev \
            asio-dev \
            protobuf-dev \
            spdlog-dev \
            cxxopts-dev \
            nlohmann-json \
            pkgconfig

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: mkckr0/audio-share
          submodules: recursive

      - name: Build
        shell: sh
        run: |
          cd server-core
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DAUDIO_SHARE_USE_VCPKG=OFF \
            -DAUDIO_SHARE_STATIC_LIBCPP=ON
          cmake --build build --target server-cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: audio-share-alpine-binary
          path: server-core/build/as-cmd
