name: Build Clipse
on:
  workflow_dispatch: null
jobs:
  build-clipse:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install System Dependencies
        run: |
          apk update
          apk add git go make build-base \
                  libx11-dev libxtst-dev libpng-dev \
                  libxkbcommon-dev xsel xclip libxcb-dev
      - name: Clone and Build Clipse
        run: |
          git clone https://github.com/savedra1/clipse
          cd clipse
          go mod tidy
          make x11
      - name: Upload Clipse Binary
        uses: actions/upload-artifact@v7
        with:
          name: clipse-alpine-x11
          path: clipse/clipse
