name: Compilar Fastfetch en Docker Debian

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
      - name: Instalar herramientas base
        run: |
          apt update
          apt install -y git build-essential cmake pkg-config \
                         libxcb1-dev libx11-dev libdrm-dev \
                         libpci-dev libgl1-mesa-dev binutils
      - name: Clonar fastfetch
        run: git clone --depth=1 https://github.com/fastfetch-cli/fastfetch.git

      - name: Compilar
        run: |
          cd fastfetch
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --target fastfetch
      
      - name: Reducir tamaño del binario (strip)
        run: |
          cd fastfetch/build
          strip --strip-all fastfetch
      
      - name: Subir binario
        uses: actions/upload-artifact@v4
        with:
          name: fastfetch
          path: fastfetch/build/fastfetch
          
