name: Build Hyfetch with muslrust
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: clux/muslrust:stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: hykilpikonna/hyfetch
          path: hyfetch

      - name: Build
        shell: sh
        run: |
          cd hyfetch
          cargo build --release --all-features
          strip target/x86_64-unknown-linux-musl/release/hyfetch

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hyfetch-static-binary
          path: hyfetch/target/x86_64-unknown-linux-musl/release/hyfetch
