name: Build Leafpad on Debian

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # base para correr Docker

    container:
      image: debian:stable-slim

    steps:
      - name: 📦 Install dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y \
            git build-essential autoconf automake \
            libgtk2.0-dev libglib2.0-dev intltool gettext

      - name: 📥 Clone Leafpad repo
        run: |
          git clone https://github.com/tarot231/leafpad.git
          cd leafpad

          autoreconf -i
          ./configure
          make

      - name: 📤 Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: leafpad
          path: leafpad/src/leafpad
