name: Build SRB2 on Nix

on:
  workflow_dispatch:

jobs:
  build-srb2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | bash
          source ~/.nix-profile/etc/profile.d/nix.sh

      - name: Build SRB2 AppImage
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix develop .#default --command bash -c "
            git clone https://github.com/Bijman/srb2bld.git &&
            cd srb2bld &&
            make install &&
            export TERM=xterm &&
            printf '1\n\n\n\n' | srb2bld --appimage
          "

      - name: Find AppImage
        id: find-appimage
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          APPIMAGE_PATH=$(find $HOME -name '*.AppImage' | head -n1)
          echo "APPIMAGE_PATH=$APPIMAGE_PATH" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: SRB2-AppImage
          path: ${{ env.APPIMAGE_PATH }}
