name: Build SRB2 AppImage

on:
  workflow_dispatch:

jobs:
  build-srb2:
    container:
      image: nixos/nix:latest  # Imagen pública con Nix preinstalado

    steps:
      - name: Checkout repo (donde está tu flake.nix)
        uses: actions/checkout@v4

      - name: Enter Nix shell and build SRB2
        run: |
          nix develop .#default --command bash -c "
            git clone https://github.com/Bijman/srb2bld.git &&
            cd srb2bld &&
            make install &&
            export TERM=xterm &&
            printf '1\n\n\n\n' | srb2bld --appimage
          "

      - name: Find generated AppImage
        id: find-appimage
        run: |
          APPIMAGE_PATH=$(find $HOME -name '*.AppImage' | head -n1)
          echo "APPIMAGE_PATH=$APPIMAGE_PATH" >> $GITHUB_ENV
          echo "AppImage generated: $APPIMAGE_PATH"

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: SRB2-AppImage
          path: ${{ env.APPIMAGE_PATH }}
