name: Build Norka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y meson python3 intltool libgranite-dev \
          libgtk-3-dev libgspell-1-dev libgtksourceview-4-dev libwebkit2gtk-4.0-dev \
          python3-gi python3-gi-cairo gir1.2-gspell-1 gir1.2-gtksource-3.0 \
          gir1.2-granite-1.0 gir1.2-webkit2-4.0 ninja-build

      - name: Configure build
        run: meson build --prefix=/usr

      - name: Build project
        run: ninja -C build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: norka-binary
          path: build/src/norka
