name: Build Norka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone Norka repository
        run: git clone https://github.com/TenderOwl/Norka.git norka-source

      - name: Install newer version of Meson
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade meson

      - name: Install build dependencies
        run: |
          cd norka-source
          sudo apt-get install -y python3 intltool libgranite-dev \
          libgtk-3-dev libgspell-1-dev libgtksourceview-4-dev libwebkit2gtk-4.0-dev \
          python3-gi python3-gi-cairo gir1.2-gspell-1 gir1.2-gtksource-3.0 \
          gir1.2-granite-1.0 gir1.2-webkit2-4.0 ninja-build

      - name: Verify Meson version
        run: |
          meson --version
          which meson

      - name: Configure build
        run: |
          cd norka-source
          meson build --prefix=/usr

      - name: Build project
        run: |
          cd norka-source
          ninja -C build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: norka-binary
          path: norka-source/build/src/norka
