name: Build Termusic
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: clux/muslrust:stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: tramhao/termusic
          path: termusic
          ref: v0.12.0

      - name: Install build dependencies
        shell: sh
        run: |
          apt-get update
          apt-get install -y protobuf-compiler libmpv-dev libdbus-1-dev

      - name: Build
        shell: sh
        run: |
          cd termusic
          cargo build --release --no-default-features --features cover,mpv --all
          strip target/x86_64-unknown-linux-musl/release/termusic
          strip target/x86_64-unknown-linux-musl/release/termusic-server

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: termusic-mpv-static
          path: |
            termusic/target/x86_64-unknown-linux-musl/release/termusic
            termusic/target/x86_64-unknown-linux-musl/release/termusic-server
