name: Build Termusic
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: tramhao/termusic
          path: termusic
          ref: v0.12.0

      - name: Install dependencies
        shell: sh
        run: |
          apk update
          apk add build-base rust cargo git protoc mpv-dev dbus-dev openssl-dev

      - name: Build
        shell: sh
        run: |
          cd termusic
          cargo build --release --no-default-features --features cover,mpv --all
          strip target/release/termusic
          strip target/release/termusic-server

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: termusic-mpv-alpine
          path: |
            termusic/target/release/termusic
            termusic/target/release/termusic-server
