---
name: Build & Sign Firefox Translator APK (ARM 32-bit, external signing)
on:
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /opt/android-sdk
      ANDROID_NDK_VERSION: 27.0.12077973
      ANDROID_HOME: /opt/android-sdk
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: >
          sudo apt-get update

          sudo apt-get install -y make g++ libc-dev wget unzip git cmake ninja-build

          sudo rm -rf /var/lib/apt/lists/*
      - name: Create Android SDK directory
        run: sudo mkdir -p $ANDROID_SDK_ROOT
      - name: Download and install Android command line tools
        run: >
          wget -q
          https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          -O cmdtools.zip

          unzip cmdtools.zip -d $ANDROID_SDK_ROOT

          mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools-temp

          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest

          mv $ANDROID_SDK_ROOT/cmdline-tools-temp/* $ANDROID_SDK_ROOT/cmdline-tools/latest/

          rm -rf $ANDROID_SDK_ROOT/cmdline-tools-temp

          rm cmdtools.zip
      - name: Update PATH for Android tools
        run: echo
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools"
          >> $GITHUB_PATH
      - name: Accept licenses and install Android SDK components
        run: >
          yes | sdkmanager --licenses

          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

          sdkmanager "ndk;${ANDROID_NDK_VERSION}"

          sdkmanager "cmake;3.22.1"
      - name: Set NDK environment variable
        run: echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/$ANDROID_NDK_VERSION" >>
          $GITHUB_ENV
      - name: Set git config for consistent abbrev
        run: git config --global core.abbrev 10
      - name: Clone Firefox Translator source
        run: >
          git clone --depth 1
          https://github.com/nubesurrealista/firefox-translator.git
      - name: Create local.properties
        run: echo "sdk.dir=${ANDROID_SDK_ROOT}" > firefox-translator/local.properties
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Decode keystore into app dir
        run: >
          echo "${{ secrets.RELEASE_KEYSTORE_B64 }}" | base64 -d >
          firefox-translator/app/nube.p12
      - name: Build unsigned release APK (ARM)
        working-directory: firefox-translator
        run: ./gradlew assembleArmRelease --stacktrace
      - name: List APKs (unsigned)
        run: find firefox-translator/app -type f -name "*.apk"
      - name: Sign APK using apksigner
        run: >
          # Busca el unsigned APK release para ARM

          APK_PATH=$(find firefox-translator/app/build/outputs/apk/arm/release -name "*-unsigned.apk" | head -n 1)

          if [ ! -f "$APK_PATH" ]; then
            echo "No se encontró el APK unsigned release para ARM"
            exit 1
          fi

          echo "APK unsigned encontrado en: $APK_PATH"

          # Firma el APK

          "$ANDROID_HOME/build-tools/$(ls $ANDROID_HOME/build-tools | sort -V | tail -n1)/apksigner" sign \
            --ks firefox-translator/app/nube.p12 \
            --ks-key-alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.RELEASE_KEY_PASSWORD }}" \
            --out app-arm-release-signed.apk \
            "$APK_PATH"
      - name: List APKs (signed)
        run: ls -lh app-arm-release-signed.apk
      - name: Upload signed APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-translator-arm-release-apk
          path: app-arm-release-signed.apk
          if-no-files-found: error
